/**
 * Central UI string dictionary. Hebrew is the default locale.
 * All user-facing text must come from here — adding a locale later
 * means adding a dictionary, not rewriting components.
 */
export const strings = {
  appName: 'מתכנן אירועים',
  workspace: {
    loading: 'טוען פרויקט…',
    loading3d: 'מכינים את התצוגה התלת־ממדית…',
    emptyCanvasHint: 'גררו פריטים מהספרייה כדי להתחיל לתכנן',
  },
  toolbar: {
    backToDashboard: 'חזרה לפרויקטים',
    undo: 'ביטול',
    redo: 'ביצוע חוזר',
    export: 'ייצוא',
    exportPng: 'תוכנית רצפה (PNG)',
    exportJson: 'קובץ פרויקט (JSON)',
    importJson: 'ייבוא מקובץ JSON…',
    grid: 'רשת',
    snap: 'הצמדה',
    labels: 'תוויות',
    view2d: '2D',
    viewSplit: 'מפוצל',
    view3d: '3D',
  },
  status: {
    saved: 'נשמר',
    saving: 'שומר…',
    saveFailed: 'השמירה נכשלה — מנסים שוב',
  },
  catalog: {
    items: {
      tableRound: 'שולחן עגול',
      tableRoundLarge: 'שולחן עגול גדול',
      tableSquare: 'שולחן מרובע',
      // the venue butts these end to end; 'בודד'/'כפול' keeps the two apart in the
      // library, which would otherwise show two items both called 'שולחן אבירים'
      tableBanquet: 'שולחן אבירים בודד',
      tableKnights: 'שולחן אבירים כפול',
      // the venue's six real chairs — the user's own names for them
      chairXWhite: 'לבן איקס',
      chairXWood: 'עץ איקס',
      chairGoldWhite: 'זהב ריפוד לבן',
      chairGoldBlack: 'זהב ריפוד שחור',
      chairBrown: 'חום',
      chairBlack: 'שחור',
      djBooth: 'עמדת DJ',
      bar: 'בר',
      buffet: 'עמדת בופה',
      plant: 'צמח',
      divider: 'מחיצה',
      // ceiling-hung — the height in each entry IS the drop from the ceiling
      lampPendant: 'מנורה תלויה',
      lampPendantCluster: 'מקבץ מנורות גיאומטרי',
      lampChandelierDiamond: 'נברשת יהלום',
      lampChandelierBasket: 'נברשת סל קריסטל',
      lampChandelierCandelabra: 'נברשת קנדלברה',
      // floor-standing despite its "chandelier" filename — see entries/decor.ts
      lampArcCrystal: 'מנורת קשת קריסטל',
      // table-top decor — the resort's real centerpiece inventory
      decorCandlestickBrass: 'פמוט פליז',
      decorVaseCeramic: 'ואזה קרמית',
      decorGobletCrystal: 'ואזות קריסטל',
      decorCandelabraCrystal: 'קנדלברה קריסטל',
      decorCandleholderCrystalA: 'מחזיקי נר קריסטל',
      decorCandleholderCrystalB: 'קנדלברת תליונים',
      decorVasesDecorative: 'סט ואזות דקורטיבי',
      decorVaseFlowersA: 'שלישיית ואזות פרח',
      decorVaseFlowersB: 'ואזת פרחים',
      decorFabricFolded: 'בד מקופל',
      decorNapkinFolded: 'מפיות מקופלות',
      decorCandleholdersGlass: 'מחזיקי נר זכוכית',
      decorCandelabrumGold: 'קנדלברום זהב',
      decorCandlestickGold: 'פמוט זהב',
      decorVasesGoldStriped: 'ואזות פסי זהב',
      decorCandelabrumGolden: 'קנדלברום מוזהב',
      decorTopiaryGreen: 'טופיארי ירוק',
      decorVasePampas: 'סידור פמפס',
      decorTulipsPink: 'צבעונים ורודים',
      decorBouquetRoses: 'זר ורדים',
      decorVasesRoseGold: 'ואזות רוז־גולד',
      decorVaseStriped: 'ואזה מפוספסת',
      decorVasesWhiteCeramic: 'ואזות קרמיקה לבנות',
      decorNapkinWhite: 'מפית לבנה',
      decorCandleholdersWood: 'מחזיקי נר עץ',
      decorCandlestickWood: 'פמוט עץ',
      decorPlaceSetting: 'ערכת סכו״ם',
    },
    categories: {
      tables: 'שולחנות',
      seating: 'ישיבה',
      bars: 'בר ומזנון',
      tableDecor: 'קישוטי שולחן',
      decor: 'עיצוב',
      structure: 'מבנה',
    },
    slots: {
      cloth: 'מפה',
      legs: 'רגליים',
      upholstery: 'ריפוד',
      frame: 'שלד',
      body: 'גוף',
      counter: 'דלפק',
      pot: 'עציץ',
      foliage: 'עלווה',
      panel: 'פאנל',
    },
  },
  library: {
    title: 'ספרייה',
    search: 'חיפוש פריטים…',
    noResults: 'אין תוצאות עבור',
    clearSearch: 'ניקוי חיפוש',
    placeHint: 'גררו ללוח או לחצו להצבה',
    collapse: 'כיווץ הספרייה',
    expand: 'הרחבת הספרייה',
  },
  presets: {
    library: 'פריסות',
    tableDesign: 'עיצוב שולחן',
    hallDesign: 'עיצוב אולם',
    layouts: 'פריסות אולם',
    choose: 'בחרו…',
    apply: 'החל',
    applyAll: 'החל על כל השולחנות',
    remove: 'הסרת העיצוב',
    fillHall: 'מלא אולם',
    fillHint: 'ממלא את השטח הפנוי בשולחנות מהפריסה שנבחרה — מוסיף בלבד, לא מזיז את הקיים',
    seatsSuffix: 'מקומות',
    items: {
      presetRound12GoldWhite: 'עגול 180 · 12 · זהב לבן',
      presetRound10XWhite: 'עגול 180 · 10 · לבן איקס',
      presetRoundLarge22GoldBlack: 'עגול 380 · 22 · זהב שחור',
      presetSquare8XWood: 'מרובע 160 · 8 · עץ איקס',
      presetBanquet12Black: 'אבירים 240 · 12 · שחור',
      presetKnights22Brown: 'אבירים 480 · 22 · חום',
      designClassicGold: 'קלאסי זהב',
      designCrystal: 'קריסטל',
      designFloralPink: 'פרחוני ורוד',
      designRusticWood: 'כפרי עץ',
      hallPendants: 'מנורות תלויות',
      hallPendantClusters: 'מקבצי מנורות',
      hallChandeliersDiamond: 'נברשות יהלום',
      hallChandeliersBasket: 'נברשות סל קריסטל',
      hallChandeliersCandelabra: 'נברשות קנדלברה',
    },
  },
  inspector: {
    projectTitle: 'פרויקט ואולם',
    projectName: 'שם הפרויקט',
    eventDate: 'תאריך האירוע',
    venue: 'האולם',
    venueName: 'שם האולם',
    venueDims: 'מידות',
    wallHeightInfo: 'גובה קירות',
    summary: 'סיכום',
    layers: 'שכבות',
    layerShow: 'הצגת השכבה',
    layerHide: 'הסתרת השכבה',
    layerLock: 'נעילת השכבה',
    layerUnlock: 'ביטול נעילת השכבה',
    layerLockedNotice: 'קטגוריית הפריט נעולה בשכבות',
    transform: 'מיקום וגודל',
    posX: 'X (מ׳)',
    posY: 'Y (מ׳)',
    width: 'רוחב (מ׳)',
    depth: 'עומק (מ׳)',
    diameter: 'קוטר (מ׳)',
    height: 'גובה (מ׳)',
    rotation: 'סיבוב (°)',
    seating: 'הושבה',
    seats: 'מקומות ישיבה',
    maxSeats: 'מקסימום',
    spacing: 'מרווח כיסאות (ס״מ)',
    chairModel: 'דגם כיסא',
    chairColors: 'צבעי הכיסאות',
    detachAll: 'ניתוק כל הכיסאות',
    removeSettings: 'הסרת ערכות סכו״ם',
    appearance: 'מראה',
    name: 'שם',
    lockedNotice: 'האובייקט נעול',
    unlock: 'ביטול נעילה',
    itemsSelected: 'פריטים נבחרו',
    align: 'יישור',
    distribute: 'פיזור',
    alignStart: 'יישור לימין הלוח',
    alignCenterX: 'מרכוז אופקי',
    alignEnd: 'יישור לשמאל הלוח',
    alignTop: 'יישור למעלה',
    alignCenterY: 'מרכוז אנכי',
    alignBottom: 'יישור למטה',
    distributeX: 'פיזור אופקי',
    distributeY: 'פיזור אנכי',
    deleteSelected: 'מחיקת הנבחרים',
    detachChair: 'ניתוק כיסא',
    belongsTo: 'משתייך לשולחן',
  },
  statusBar: {
    tables: 'שולחנות',
    chairs: 'כיסאות',
    seats: 'מקומות',
    zoomFit: 'התאמה לאולם',
    zoomIn: 'התקרבות',
    zoomOut: 'התרחקות',
  },
  viewMode: {
    d2: '2D',
    split: 'מפוצל',
    d3: '3D',
    placeholder3d: 'התצוגה התלת־ממדית תגיע בקרוב',
  },
  drill: {
    chair: 'כיסא',
    decor: 'קישוט שולחן',
    escHint: 'Esc לחזרה',
  },
  help: {
    title: 'קיצורי מקלדת',
    close: 'סגירה',
    rows: [
      ['V / H', 'כלי בחירה / כלי יד'],
      ['Space (החזקה)', 'הזזת תצוגה זמנית'],
      ['גלגלת עכבר', 'זום אל הסמן'],
      ['Ctrl+Z / Ctrl+Y', 'ביטול / ביצוע חוזר'],
      ['Ctrl+D', 'שכפול'],
      ['Ctrl+C / X / V', 'העתקה / גזירה / הדבקה'],
      ['Delete', 'מחיקת הנבחרים'],
      ['Ctrl+A', 'בחירת הכול'],
      ['חצים', 'הזזה 10 ס״מ (Shift: מטר · Alt: ס״מ)'],
      ['R / Shift+R', 'סיבוב 90° עם/נגד כיוון השעון'],
      ['Shift בסיבוב', 'צעדים של 15°'],
      ['G / Shift+G', 'הצגת רשת / הצמדה'],
      ['Alt בזמן גרירה', 'עקיפת הצמדה'],
      ['Shift+1 / Shift+2', 'התאמה לאולם / לבחירה'],
      ['Ctrl+0', 'תצוגה 100%'],
      ['דאבל־קליק על כיסא', 'בחירת כיסא בודד'],
      ['Esc', 'ביטול בחירה / יציאה'],
      ['?', 'חלונית זו'],
    ],
    title3d: 'ניווט בתלת־ממד (כמו בלומיון)',
    rows3d: [
      ['W / A / S / D / חצים', 'תנועה: קדימה / שמאלה / אחורה / ימינה'],
      ['Q / E', 'עלייה / ירידה'],
      ['Shift · Space · Shift+Space', 'מהיר · איטי מאוד · מהיר מאוד'],
      ['לחצן ימני + גרירה', 'מבט חופשי'],
      ['לחצן אמצעי + גרירה', 'הזזת המבט הצידה'],
      ['גלגלת', 'תנועה קדימה / אחורה'],
      ['O + לחצן ימני', 'סיבוב סביב המוקד'],
      ['Ctrl+H', 'יישור המבט לאופק'],
      ['דאבל־קליק ימני', 'קפיצה לנקודה'],
      ['קליק שמאלי', 'בחירת פריט'],
    ],
  },
  menu: {
    duplicate: 'שכפול',
    copy: 'העתקה',
    cut: 'גזירה',
    paste: 'הדבקה',
    pasteHere: 'הדבקה כאן',
    delete: 'מחיקה',
    rotate90: 'סיבוב 90°',
    bringForward: 'הבא קדימה',
    sendBackward: 'שלח אחורה',
    bringToFront: 'הבא לחזית',
    sendToBack: 'שלח לרקע',
    lock: 'נעילה',
    unlock: 'ביטול נעילה',
    selectAll: 'בחירת הכול',
    fitVenue: 'התאמה לאולם',
    zoom100: 'תצוגה 100%',
    detachChair: 'ניתוק כיסא',
    detachAll: 'ניתוק כל הכיסאות',
    deleteChair: 'מחיקת כיסא',
  },
} as const
