/**
 * Central UI string dictionary. Hebrew is the default locale.
 * All user-facing text must come from here — adding a locale later
 * means adding a dictionary, not rewriting components.
 */
export const strings = {
  appName: 'מתכנן אירועים',
  workspace: {
    loading: 'טוען פרויקט…',
    loading3d: 'מכינים את התצוגה התלת־ממדית…',
    emptyCanvasHint: 'גררו פריטים מהספרייה כדי להתחיל לתכנן',
  },
  toolbar: {
    backToDashboard: 'חזרה לפרויקטים',
    undo: 'ביטול',
    redo: 'ביצוע חוזר',
    export: 'ייצוא',
    exportPng: 'תוכנית רצפה (PNG)',
    exportJson: 'קובץ פרויקט (JSON)',
    importJson: 'ייבוא מקובץ JSON…',
    grid: 'רשת',
    snap: 'הצמדה',
    labels: 'תוויות',
    view2d: '2D',
    viewSplit: 'מפוצל',
    view3d: '3D',
  },
  status: {
    saved: 'נשמר',
    saving: 'שומר…',
    saveFailed: 'השמירה נכשלה — מנסים שוב',
  },
  catalog: {
    items: {
      tableRound: 'שולחן עגול',
      tableRect: 'שולחן מלבני',
      tableSquare: 'שולחן מרובע',
      tableBanquet: 'שולחן אבירים',
      tableCocktail: 'שולחן קוקטייל',
      chairBanquet: 'כיסא בנקט',
      chairChiavari: "כיסא צ'יאבארי",
      stage: 'במה',
      danceFloor: 'רחבת ריקודים',
      djBooth: 'עמדת DJ',
      bar: 'בר',
      buffet: 'עמדת בופה',
      plant: 'צמח',
      divider: 'מחיצה',
    },
    categories: {
      tables: 'שולחנות',
      seating: 'ישיבה',
      staging: 'במה וריקודים',
      bars: 'בר ומזנון',
      decor: 'עיצוב',
      structure: 'מבנה',
    },
    slots: {
      cloth: 'מפה',
      legs: 'רגליים',
      upholstery: 'ריפוד',
      frame: 'שלד',
      deck: 'משטח',
      skirt: 'חיפוי במה',
      floor: 'רצפה',
      body: 'גוף',
      counter: 'דלפק',
      pot: 'עציץ',
      foliage: 'עלווה',
      panel: 'פאנל',
    },
  },
  library: {
    title: 'ספרייה',
    search: 'חיפוש פריטים…',
    noResults: 'אין תוצאות עבור',
    clearSearch: 'ניקוי חיפוש',
    placeHint: 'גררו ללוח או לחצו להצבה',
    collapse: 'כיווץ הספרייה',
    expand: 'הרחבת הספרייה',
  },
  inspector: {
    projectTitle: 'פרויקט ואולם',
    projectName: 'שם הפרויקט',
    eventDate: 'תאריך האירוע',
    venue: 'האולם',
    venueWidth: 'רוחב (מ׳)',
    venueDepth: 'עומק (מ׳)',
    wallHeight: 'גובה קירות (מ׳)',
    floorColor: 'צבע רצפה',
    transform: 'מיקום וגודל',
    posX: 'X (מ׳)',
    posY: 'Y (מ׳)',
    width: 'רוחב (מ׳)',
    depth: 'עומק (מ׳)',
    diameter: 'קוטר (מ׳)',
    height: 'גובה (מ׳)',
    rotation: 'סיבוב (°)',
    seating: 'הושבה',
    seats: 'מקומות ישיבה',
    maxSeats: 'מקסימום',
    spacing: 'מרווח כיסאות (ס״מ)',
    chairModel: 'דגם כיסא',
    chairColors: 'צבעי הכיסאות',
    detachAll: 'ניתוק כל הכיסאות',
    appearance: 'מראה',
    name: 'שם',
    lockedNotice: 'האובייקט נעול',
    unlock: 'ביטול נעילה',
    itemsSelected: 'פריטים נבחרו',
    align: 'יישור',
    distribute: 'פיזור',
    alignStart: 'יישור לימין הלוח',
    alignCenterX: 'מרכוז אופקי',
    alignEnd: 'יישור לשמאל הלוח',
    alignTop: 'יישור למעלה',
    alignCenterY: 'מרכוז אנכי',
    alignBottom: 'יישור למטה',
    distributeX: 'פיזור אופקי',
    distributeY: 'פיזור אנכי',
    deleteSelected: 'מחיקת הנבחרים',
    detachChair: 'ניתוק כיסא',
    belongsTo: 'משתייך לשולחן',
  },
  statusBar: {
    tables: 'שולחנות',
    chairs: 'כיסאות',
    seats: 'מקומות',
    zoomFit: 'התאמה לאולם',
    zoomIn: 'התקרבות',
    zoomOut: 'התרחקות',
  },
  viewMode: {
    d2: '2D',
    split: 'מפוצל',
    d3: '3D',
    placeholder3d: 'התצוגה התלת־ממדית תגיע בקרוב',
  },
  drill: {
    chair: 'כיסא',
    escHint: 'Esc לחזרה',
  },
  help: {
    title: 'קיצורי מקלדת',
    close: 'סגירה',
    rows: [
      ['V / H', 'כלי בחירה / כלי יד'],
      ['Space (החזקה)', 'הזזת תצוגה זמנית'],
      ['גלגלת עכבר', 'זום אל הסמן'],
      ['Ctrl+Z / Ctrl+Y', 'ביטול / ביצוע חוזר'],
      ['Ctrl+D', 'שכפול'],
      ['Ctrl+C / X / V', 'העתקה / גזירה / הדבקה'],
      ['Delete', 'מחיקת הנבחרים'],
      ['Ctrl+A', 'בחירת הכול'],
      ['חצים', 'הזזה 10 ס״מ (Shift: מטר · Alt: ס״מ)'],
      ['R / Shift+R', 'סיבוב 90° עם/נגד כיוון השעון'],
      ['Shift בסיבוב', 'צעדים של 15°'],
      ['G / Shift+G', 'הצגת רשת / הצמדה'],
      ['Alt בזמן גרירה', 'עקיפת הצמדה'],
      ['Shift+1 / Shift+2', 'התאמה לאולם / לבחירה'],
      ['Ctrl+0', 'תצוגה 100%'],
      ['דאבל־קליק על כיסא', 'בחירת כיסא בודד'],
      ['Esc', 'ביטול בחירה / יציאה'],
      ['?', 'חלונית זו'],
    ],
  },
  menu: {
    duplicate: 'שכפול',
    copy: 'העתקה',
    cut: 'גזירה',
    paste: 'הדבקה',
    pasteHere: 'הדבקה כאן',
    delete: 'מחיקה',
    rotate90: 'סיבוב 90°',
    bringForward: 'הבא קדימה',
    sendBackward: 'שלח אחורה',
    bringToFront: 'הבא לחזית',
    sendToBack: 'שלח לרקע',
    lock: 'נעילה',
    unlock: 'ביטול נעילה',
    selectAll: 'בחירת הכול',
    fitVenue: 'התאמה לאולם',
    zoom100: 'תצוגה 100%',
    detachChair: 'ניתוק כיסא',
    detachAll: 'ניתוק כל הכיסאות',
    deleteChair: 'מחיקת כיסא',
  },
} as const
