/**
 * AUTO-GENERATED by tools/bake-plugin.ts — do not edit by hand.
 *
 * Baked venue fixtures: objects that belong to the hall itself rather than to a
 * single event. `createDefaultScene` seeds them into every new project, and
 * `flags.frozen` makes them un-movable, un-deletable and un-unlockable.
 *
 * This file is self-sufficient. When the temporary bake button is removed from
 * the toolbar the fixtures stay exactly as they are — nothing else changes.
 *
 * Empty until the first bake: the arrangement is the user's to decide (source
 * doc §16), so no placeholder furniture is committed here.
 */
import type { SceneObject } from './model/types'

export const VENUE_FIXTURES: Record<string, SceneObject[]> = {}
