/**
 * AUTO-GENERATED by tools/bake-plugin.ts — do not edit by hand.
 * Generated: 2026-07-30T14:08:43.512Z  ·  venue: resort
 *
 * Baked venue fixtures: objects that belong to the hall itself rather than to a
 * single event. `createDefaultScene` seeds them into every new project.
 *
 * A TREE, not a list. Roots come first and each is followed by its attached
 * children, whose `transform` is parent-relative and whose `parentId` points at
 * the root's id IN THIS FILE. Only roots carry `flags.frozen`, which makes them
 * un-movable, un-deletable and un-unlockable; the chairs and decor on them stay
 * selectable, or the user could never dress a table again.
 *
 * Re-baking is CUMULATIVE: the button sends the frozen fixtures back along with
 * everything else, so a second press rewrites this file rather than emptying it.
 *
 * This file is self-sufficient. When the temporary bake button is removed from
 * the presets panel the fixtures stay exactly as they are — nothing else changes.
 */
import type { SceneObject } from './model/types'

export const VENUE_FIXTURES: Record<string, SceneObject[]> = {
  "resort": [
    {"id":"fixture-resort-001","catalogId":"bar.back-wall","name":"קיר מאחורי הבר","transform":{"position":{"x":2189,"y":42.95},"rotation":180,"elevation":0},"size":{"width":188.9,"depth":85.9,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-002","catalogId":"bar.resort-left","name":"בר ריזורט שמאל","transform":{"position":{"x":2059.1,"y":275.65},"rotation":180,"elevation":0},"size":{"width":259.8,"depth":139.5,"height":157},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-003","catalogId":"bar.resort-right","name":"בר ריזורט ימין","transform":{"position":{"x":2318.9,"y":275.65},"rotation":180,"elevation":0},"size":{"width":259.8,"depth":139.5,"height":157},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-004","catalogId":"plant.potted","name":"","transform":{"position":{"x":3870,"y":1500},"rotation":0,"elevation":0},"size":{"width":151.5,"depth":141.9,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-005","catalogId":"plant.potted","name":"","transform":{"position":{"x":870,"y":1500},"rotation":0,"elevation":0},"size":{"width":151.5,"depth":141.9,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-006","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":4370,"y":1930},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-007","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":4380,"y":1450},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-008","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":4380,"y":1060},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-009","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":4380,"y":190},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-010","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":4060,"y":40},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-011","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":3700,"y":40},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-012","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":3340,"y":40},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-013","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":2900,"y":40},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-014","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":2660,"y":32.84040927886963},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-015","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":1710,"y":40},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-016","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":1220,"y":40},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-017","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":760,"y":40},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-018","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":352.84040927886963,"y":32.84040927886963},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-019","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":40,"y":520},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-020","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":40,"y":80},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-021","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":50,"y":890},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-022","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":40,"y":1300},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-023","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":40,"y":1680},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-024","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":40,"y":2030},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-025","catalogId":"plant.potted-2","name":"","transform":{"position":{"x":40,"y":2410},"rotation":0,"elevation":0},"size":{"width":71.25,"depth":65.7,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
  ],
}
