/**
 * AUTO-GENERATED by tools/bake-plugin.ts — do not edit by hand.
 * Generated: 2026-07-28T19:27:55.319Z  ·  venue: resort
 *
 * Baked venue fixtures: objects that belong to the hall itself rather than to a
 * single event. `createDefaultScene` seeds them into every new project, and
 * `flags.frozen` makes them un-movable, un-deletable and un-unlockable.
 *
 * This file is self-sufficient. When the temporary bake button is removed from
 * the toolbar the fixtures stay exactly as they are — nothing else changes.
 */
import type { SceneObject } from './model/types'

export const VENUE_FIXTURES: Record<string, SceneObject[]> = {
  "resort": [
    {"id":"fixture-resort-001","catalogId":"bar.back-wall","name":"קיר מאחורי הבר","transform":{"position":{"x":2189,"y":42.95},"rotation":180,"elevation":0},"size":{"width":188.9,"depth":85.9,"height":240},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-002","catalogId":"bar.resort-left","name":"בר ריזורט שמאל","transform":{"position":{"x":2059.1,"y":275.65},"rotation":180,"elevation":0},"size":{"width":259.8,"depth":139.5,"height":157},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
    {"id":"fixture-resort-003","catalogId":"bar.resort-right","name":"בר ריזורט ימין","transform":{"position":{"x":2318.9,"y":275.65},"rotation":180,"elevation":0},"size":{"width":259.8,"depth":139.5,"height":157},"parentId":null,"appearance":{},"flags":{"locked":true,"visible":true,"frozen":true},"meta":{"fixture":true}},
  ],
}
