/**
 * bake-plugin — dev-only endpoint behind the toolbar's "קיבוע" button. It writes
 * the current arrangement into `src/core/venueFixtures.ts`, a normal source file
 * that `createDefaultScene` seeds every new project from (source doc §16).
 *
 * Why a source file and not IndexedDB: the point of the button is that the
 * arrangement outlives the button. Once the fixtures are decided the button can
 * be deleted and nothing else has to change — `venueFixtures.ts` stays in the
 * repo, `factory.ts` keeps seeding it, and `flags.frozen` keeps the objects
 * un-movable and un-deletable.
 *
 * SECURITY. This writes into the repo on request from a browser page, so it is
 * deliberately narrow:
 * - `apply: 'serve'` — never mounted by `vite build`/`preview`.
 * - The destination path is a module constant. Nothing in the request reaches it.
 * - The one client string that lands in the generated source (the venue id) is
 *   allowlisted to `[a-z0-9-]`; everything else is re-serialised through
 *   JSON.stringify of already-parsed JSON, which cannot emit code.
 * - The caller shows a confirm dialog first — see Toolbar.tsx.
 *
 * .ts, like capture-plugin.ts, because vite.config.ts imports it.
 */
import { writeFileSync } from 'node:fs'
import type { IncomingMessage } from 'node:http'
import { fileURLToPath } from 'node:url'
import type { Plugin } from 'vite'

/** Fixed destination. Never derived from the request. */
const OUT_FILE = fileURLToPath(new URL('../src/core/venueFixtures.ts', import.meta.url))

const MAX_BODY = 8 * 1024 * 1024
const VENUE_ID = /^[a-z0-9-]{1,40}$/
const MAX_OBJECTS = 2000

function readBody(req: IncomingMessage): Promise<string> {
  return new Promise((ok, fail) => {
    let size = 0
    const chunks: Buffer[] = []
    req.on('data', (c: Buffer) => {
      size += c.length
      if (size > MAX_BODY) {
        fail(new Error('body too large'))
        req.destroy()
        return
      }
      chunks.push(c)
    })
    req.on('end', () => ok(Buffer.concat(chunks).toString('utf8')))
    req.on('error', fail)
  })
}

/**
 * Deterministic ids (`fixture-<venue>-001`) rather than nanoid: baking twice from
 * the same arrangement must produce the same file, or every bake is a diff and
 * two machines never agree.
 */
export function bakeSource(venueId: string, objects: unknown[], now: string): string {
  const withIds = objects.map((raw, i) => {
    const object = raw as Record<string, unknown>
    return {
      ...object,
      id: `fixture-${venueId}-${String(i + 1).padStart(3, '0')}`,
      parentId: null,
      flags: { locked: true, visible: true, frozen: true },
      meta: { ...(object.meta as object | undefined), fixture: true },
    }
  })
  const body = withIds.map((o) => `    ${JSON.stringify(o)},`).join('\n')
  return `/**
 * AUTO-GENERATED by tools/bake-plugin.ts — do not edit by hand.
 * Generated: ${now}  ·  venue: ${venueId}
 *
 * Baked venue fixtures: objects that belong to the hall itself rather than to a
 * single event. \`createDefaultScene\` seeds them into every new project, and
 * \`flags.frozen\` makes them un-movable, un-deletable and un-unlockable.
 *
 * This file is self-sufficient. When the temporary bake button is removed from
 * the toolbar the fixtures stay exactly as they are — nothing else changes.
 */
import type { SceneObject } from './model/types'

export const VENUE_FIXTURES: Record<string, SceneObject[]> = {
  ${JSON.stringify(venueId)}: [
${body}
  ],
}
`
}

export function bakePlugin(): Plugin {
  return {
    name: 'hanan-bake',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/__bake', async (req, res, next) => {
        if (req.method !== 'POST') return next()
        const send = (code: number, payload: unknown) => {
          res.statusCode = code
          res.setHeader('content-type', 'application/json; charset=utf-8')
          res.end(JSON.stringify(payload))
        }
        try {
          const { venueId, objects } = JSON.parse(await readBody(req)) as {
            venueId?: unknown
            objects?: unknown
          }
          if (typeof venueId !== 'string' || !VENUE_ID.test(venueId)) {
            return send(400, { error: 'bad venue id' })
          }
          if (!Array.isArray(objects) || objects.length > MAX_OBJECTS) {
            return send(400, { error: 'expected an object array' })
          }
          writeFileSync(OUT_FILE, bakeSource(venueId, objects, new Date().toISOString()), 'utf8')
          server.config.logger.info(`baked ${objects.length} fixtures → ${OUT_FILE}`)
          send(200, { count: objects.length })
        } catch (err) {
          send(500, { error: err instanceof Error ? err.message : String(err) })
        }
      })
    },
  }
}
