#!/usr/bin/env node
/**
 * textures-prep — cut the fabric swatch sheet into rectangles, then install the
 * textures that Higgsfield generated from them.
 *
 * The sheet is a contact sheet of fabric samples separated by near-white gutters.
 * The grid is NOT hardcoded: `cut` derives it by scanning row-mean and column-mean
 * luminance, splitting on the gutters, and then ASSERTING the result. A sheet that
 * does not resolve to a clean grid stops the script instead of guessing, because a
 * mis-detected box would silently produce a texture of the wrong fabric.
 *
 * A crop is only how we POINT AT a rectangle. The deliverable textures are
 * generated by Higgsfield (image-to-image, seamless/tileable) with the crop as the
 * reference image — see Plans/R3/handoff/05-textures.md.
 *
 * Commands
 *   cut      detect the grid, write crops + boxes.json to .tmp/textures-src/
 *   put      PUT each crop to its Higgsfield presigned upload_url (.tmp/textures-src/uploads.json)
 *   install  download generated images listed in .tmp/textures-src/results.json
 *            into public/textures/, or fall back to the local crop
 *   measure  print the measurement table for whatever is in public/textures/
 *
 * How it was run (repo root, 2026-07-29):
 *   node tools/textures-prep.mjs cut
 *   node tools/textures-prep.mjs put
 *   node tools/textures-prep.mjs install
 *   node tools/textures-prep.mjs measure
 *
 * Ordering: rectangles are numbered ROW-MAJOR, LEFT COLUMN FIRST.
 *   row 1 left = 01, row 1 right = 02, row 2 left = 03, ... row 11 right = 22.
 */
import sharp from 'sharp'
import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile, readdir, stat } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SRC_DIR = path.join(ROOT, '.tmp', 'textures-src')
const OUT_DIR = path.join(ROOT, 'public', 'textures')

const DEFAULT_SHEET =
  'D:\\משה פרוייקטים\\פיתוח אתרים\\HANAN-APP-DOCS\\GPT\\צבעי מפות ומפיות\\hf_20260728_115548_7aff0194-754a-4ae5-a5d6-13ac84db4a0e.png'

/** Expected grid. The detector must land exactly here or stop. */
const EXPECT_COLS = 2
const EXPECT_ROWS = 11

/**
 * A gutter line is bright AND flat. Brightness alone is not enough: several
 * swatches on this sheet are near-white cream linen and their mean luminance is
 * within a few levels of the paper. What separates them is variance — woven cloth
 * always has some, the gutter has almost none.
 */
const GUTTER_MEAN_MIN = 244
const GUTTER_SD_MAX = 7
/** Runs shorter than this are anti-aliasing on a band edge, not a band. */
const MIN_BAND_PX = 24

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`)
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback
}

/** Per-line mean and standard deviation along one axis of a greyscale buffer. */
function profile(data, width, height, axis) {
  const n = axis === 'row' ? height : width
  const m = axis === 'row' ? width : height
  const out = []
  for (let i = 0; i < n; i++) {
    let sum = 0
    let sumSq = 0
    for (let j = 0; j < m; j++) {
      const v = axis === 'row' ? data[i * width + j] : data[j * width + i]
      sum += v
      sumSq += v * v
    }
    const mean = sum / m
    out.push({ mean, sd: Math.sqrt(Math.max(0, sumSq / m - mean * mean)) })
  }
  return out
}

/** Contiguous runs of non-gutter lines, i.e. the bands that hold content. */
function bands(stats) {
  const runs = []
  let start = -1
  for (let i = 0; i < stats.length; i++) {
    const isGutter = stats[i].mean >= GUTTER_MEAN_MIN && stats[i].sd <= GUTTER_SD_MAX
    if (!isGutter && start === -1) start = i
    if (isGutter && start !== -1) {
      runs.push([start, i - 1])
      start = -1
    }
  }
  if (start !== -1) runs.push([start, stats.length - 1])
  return runs.filter(([a, b]) => b - a + 1 >= MIN_BAND_PX)
}

async function detect(sheet) {
  const { data, info } = await sharp(sheet)
    .greyscale()
    .raw()
    .toBuffer({ resolveWithObject: true })
  const { width, height } = info
  console.log(`sheet: ${sheet}`)
  console.log(`size:  ${width} x ${height}`)

  const colBands = bands(profile(data, width, height, 'col'))
  const rowBands = bands(profile(data, width, height, 'row'))
  console.log(`detected ${colBands.length} column band(s), ${rowBands.length} row band(s)`)
  console.log(`  columns: ${colBands.map(([a, b]) => `${a}-${b}`).join('  ')}`)
  console.log(`  rows:    ${rowBands.map(([a, b]) => `${a}-${b}`).join('  ')}`)

  if (colBands.length !== EXPECT_COLS || rowBands.length !== EXPECT_ROWS) {
    throw new Error(
      `grid assertion failed: got ${colBands.length} x ${rowBands.length} ` +
        `(= ${colBands.length * rowBands.length} boxes), expected ${EXPECT_COLS} x ${EXPECT_ROWS} ` +
        `(= ${EXPECT_COLS * EXPECT_ROWS}). Refusing to guess — inspect the sheet or the thresholds.`,
    )
  }

  // row-major, left column first
  const boxes = []
  for (const [y0, y1] of rowBands) {
    for (const [x0, x1] of colBands) {
      boxes.push({
        index: boxes.length + 1,
        left: x0,
        top: y0,
        width: x1 - x0 + 1,
        height: y1 - y0 + 1,
      })
    }
  }
  return { boxes, width, height }
}

async function cmdCut() {
  const sheet = arg('sheet', DEFAULT_SHEET)
  const { boxes } = await detect(sheet)
  await mkdir(SRC_DIR, { recursive: true })

  console.log('\nindex  box (x,y,w,h)              crop file')
  for (const b of boxes) {
    const name = `rect-${String(b.index).padStart(2, '0')}.png`
    await sharp(sheet)
      .extract({ left: b.left, top: b.top, width: b.width, height: b.height })
      .png()
      .toFile(path.join(SRC_DIR, name))
    console.log(
      `${String(b.index).padStart(5)}  ` +
        `(${b.left},${b.top},${b.width},${b.height})`.padEnd(26) +
        `  ${name}`,
    )
  }
  await writeFile(
    path.join(SRC_DIR, 'boxes.json'),
    JSON.stringify({ sheet, boxes }, null, 2),
    'utf8',
  )
  console.log(`\n${boxes.length} crops -> ${SRC_DIR}`)
}

/**
 * Higgsfield's media_upload hands back presigned PUT urls; the bytes are ours to
 * send. uploads.json is [{ index, upload_url }].
 */
async function cmdPut() {
  const jobs = JSON.parse(await readFile(path.join(SRC_DIR, 'uploads.json'), 'utf8'))
  for (const job of jobs) {
    const name = `rect-${String(job.index).padStart(2, '0')}.png`
    const body = await readFile(path.join(SRC_DIR, name))
    const res = await fetch(job.upload_url, {
      method: 'PUT',
      headers: { 'Content-Type': 'image/png' },
      body,
    })
    if (!res.ok) throw new Error(`PUT ${name} failed: ${res.status} ${res.statusText}`)
    console.log(`put ${name} (${body.length} bytes) -> ${res.status}`)
  }
}

/**
 * results.json is [{ index, url }] with url = the generated image, or null to
 * fall back to the local crop. A hole is never acceptable (see 05-textures.md);
 * a fallback row is marked in the measurement table instead.
 *
 * Output is WEBP, not PNG. The 22 generated PNGs weigh 42MB, which is as much as
 * the entire GLB prop library, and only three of them are referenced today — the
 * rest are a palette. At q90 the same images are ~8x smaller with no visible
 * difference on a tablecloth, and `.webp` is already the project's texture format
 * for thumbnails. Both sizes are recorded in handoff/05-textures.md.
 */
const WEBP_QUALITY = 90

async function cmdInstall() {
  const results = JSON.parse(await readFile(path.join(SRC_DIR, 'results.json'), 'utf8'))
  await mkdir(OUT_DIR, { recursive: true })
  for (const r of results) {
    const n = String(r.index).padStart(2, '0')
    const out = path.join(OUT_DIR, `fabric-${n}.webp`)
    let input
    let origin
    if (r.url) {
      const res = await fetch(r.url)
      if (!res.ok) throw new Error(`GET ${r.url} failed: ${res.status}`)
      input = Buffer.from(await res.arrayBuffer())
      origin = 'higgsfield'
    } else {
      input = await readFile(path.join(SRC_DIR, `rect-${n}.png`))
      origin = 'local crop (fallback)'
    }
    await sharp(input).webp({ quality: WEBP_QUALITY }).toFile(out)
    const after = (await stat(out)).size
    console.log(
      `fabric-${n}.webp <- ${origin}  ${input.length} B png -> ${after} B webp ` +
        `(${(input.length / after).toFixed(1)}x)`,
    )
  }
}

async function cmdMeasure() {
  const boxesPath = path.join(SRC_DIR, 'boxes.json')
  let boxes = []
  try {
    boxes = JSON.parse(await readFile(boxesPath, 'utf8')).boxes
  } catch {
    console.log('(no boxes.json — source boxes column will be blank)')
  }
  const files = (await readdir(OUT_DIR)).filter((f) => /^fabric-\d\d\.(png|webp)$/.test(f)).sort()
  console.log('| # | source box (x,y,w,h) | file | resolution | bytes | sha256 |')
  console.log('|---|---|---|---|---|---|')
  for (const f of files) {
    const i = Number(f.slice(7, 9))
    const p = path.join(OUT_DIR, f)
    const buf = await readFile(p)
    const meta = await sharp(buf).metadata()
    const b = boxes.find((x) => x.index === i)
    const box = b ? `${b.left},${b.top},${b.width},${b.height}` : '—'
    const sha = createHash('sha256').update(buf).digest('hex').slice(0, 12)
    console.log(
      `| ${i} | ${box} | ${f} | ${meta.width}x${meta.height} | ${(await stat(p)).size} | ${sha} |`,
    )
  }
}

const cmd = process.argv[2]
const table = { cut: cmdCut, put: cmdPut, install: cmdInstall, measure: cmdMeasure }
if (!table[cmd]) {
  console.error(`usage: node tools/textures-prep.mjs <cut|put|install|measure> [--sheet <path>]`)
  process.exit(1)
}
await table[cmd]()
